language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:

  - docker --version
# Build
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-frontend ./udagram-frontend

  # Tagging
  - docker tag reverseproxy khanq/reverseproxy:v1
  - docker tag udagram-api-user khanq/udagram-api-user:v1
  - docker tag udagram-api-feed khanq/udagram-api-feed:v1
  - docker tag udagram-frontend:latest khanq/udagram-front:v1

after_success:
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push khanq/reverseproxy:v1
  - docker push khanq/udagram-api-user:v1
  - docker push khanq/udagram-api-feed:v1
  - docker push khanq/udagram-front:v1
  # Do similar for other three images